sequenceDiagram

    actor User
    participant FE_ARp
    participant Checkout

    note right of User: User is authenticated
    note right of User: The payment notice has been generated

    User ->> FE_ARp : Request spontaneous payment
    FE_ARp ->> Checkout : POST /carts <br> {amount, payment notice data, redirectUrl}

    activate FE_ARp
        activate Checkout
        note right of Checkout: Payment is finalized
            Checkout -->> FE_ARp : Payment confirmation
        deactivate Checkout
        FE_ARp -->> User : #
    deactivate FE_ARp
