sequenceDiagram
    actor User
    participant FE_ARp
    participant BE_ARp
    participant DB as DATABASE
    participant MANAGER as DEBT-POSITION-MANAGER-FOR-THE-ORGANIZATION

    note right of User: User authenticated
    note right of User: The User selected the Organization
    note over User, MANAGER : Retrieve Spontaneous List

    User ->> FE_ARp : Access to Spontaneous List
    activate FE_ARp
        FE_ARp ->> BE_ARp : GET /spontaneousList <br> Authentication: Bearer <Session Token>
        activate BE_ARp
            BE_ARp ->> BE_ARp : Validate session token
            alt Token Invalid or Expired
                BE_ARp ->> FE_ARp : 401 Unauthorized (Token Invalid or Expired)
            else Token valid
                BE_ARp ->> DB : Get MANAGER baseURL for Organization
                activate DB
                    DB ->> BE_ARp : Return baseURL
                deactivate DB

                BE_ARp ->> MANAGER : GET {baseURL}/spontaneousList <br> Authentication: Bearer <Session Token>
                activate MANAGER
                    MANAGER ->> BE_ARp : Return spontaneous list (with Token)
                deactivate MANAGER

                BE_ARp ->> BE_ARp : Validate token received from MANAGER
                alt Token Invalid or Expired
                    BE_ARp ->> FE_ARp : 401 Unauthorized (Token Invalid or Expired)
                else Token valid
                    BE_ARp -->> FE_ARp : 200 OK <br> Spontaneous list data
                end
            end
        deactivate BE_ARp
        FE_ARp -->> User: Display spontaneous list
    deactivate FE_ARp