sequenceDiagram

actor User
participant FE_ARp
participant BE_ARp
participant DB as DATABASE
participant MANAGER as DEBT-POSITION-MANAGER-FOR-THE-ORGANIZATION

note right of User: User authenticated
note over User, MANAGER : Retrieve Spontaneous Details

User ->> FE_ARp : Select the Spontaneous type
activate FE_ARp
    FE_ARp ->> BE_ARp : GET //organizations/{paTaxCode}/spontaneous-types/{id} <br> Authentication: Bearer <Session Token>
    activate BE_ARp
        BE_ARp ->> BE_ARp : Validate session token

        alt Token Invalid or Expired
            BE_ARp ->> FE_ARp : 401 Unauthorized (Token Invalid or Expired)
        else Token valid
            BE_ARp ->> DB : Get MANAGER baseURL, clientId and clientSecret for Organization

            activate DB
                DB ->> BE_ARp : Return baseURL, clientId and clientSecret
            deactivate DB

            BE_ARp ->> MANAGER : POST {baseURL}/postToken <br> clientId, clientSecret
            activate MANAGER
                MANAGER ->> BE_ARp : Return new token
            deactivate MANAGER
            note right of BE_ARp : Token cached for MANAGER

            BE_ARp ->> MANAGER : GET {baseURL}/spontaneousDetails <br> Authentication: Token (cached or newly obtained)

            activate MANAGER
                MANAGER ->> MANAGER: Validate token
                alt Token Invalid or Expired
                    MANAGER ->> BE_ARp : 401 Unauthorized (Token Invalid or Expired)
                else Token valid
                    MANAGER ->> BE_ARp : Return spontaneous details
                end
            deactivate MANAGER

            BE_ARp -->> FE_ARp : 200 OK <br> Spontaneous details
        end
    deactivate BE_ARp

    note over User,FE_ARp : [PHASE 1] FE_ARp retrieves the details <br> and shows the form <br> N.B. In this phase, only the following <br> will be shown to the user: <br> - default form, <br> - form with fixed amount, <br> - external URL

    FE_ARp -->> User: Display Form
deactivate FE_ARp